services:
  app:
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - 8001:80
    depends_on:
      - mariadb
      - redis
    volumes:
      - nextcloud-data:/var/www/html
      # - ./nextcloud-config.php:/var/www/html/config/config.php
      - /mnt/d/Nextcloud:/var/www/data
    environment:
      - PUID=1000
      - PGID=1000
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - MYSQL_HOST=mariadb
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis

  mariadb:
    image: mariadb:jammy
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_INITDB_SKIP_TZINFO=1
      - MARIADB_DATABASE=${DB_DEFAULT}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  nextcloud-data:
    name: cloud_nextcloud-data
  mariadb-data:
    name: cloud_db-data
  redis-data:
    name: cloud_redis-data
